//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresenceSimulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9123")]
        public int BroadcastPort {
            get {
                return ((int)(this["BroadcastPort"]));
            }
            set {
                this["BroadcastPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9125")]
        public int updateProviderPort {
            get {
                return ((int)(this["updateProviderPort"]));
            }
            set {
                this["updateProviderPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int BroadcastPeriod {
            get {
                return ((int)(this["BroadcastPeriod"]));
            }
            set {
                this["BroadcastPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string TCPServerPeriod {
            get {
                return ((string)(this["TCPServerPeriod"]));
            }
            set {
                this["TCPServerPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9124")]
        public int statusProviderPort {
            get {
                return ((int)(this["statusProviderPort"]));
            }
            set {
                this["statusProviderPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting {
            get {
                return ((int)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tracks\\")]
        public string userTrackFolder {
            get {
                return ((string)(this["userTrackFolder"]));
            }
            set {
                this["userTrackFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int locationUpdateInterval {
            get {
                return ((int)(this["locationUpdateInterval"]));
            }
            set {
                this["locationUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecordUserTracks {
            get {
                return ((bool)(this["RecordUserTracks"]));
            }
            set {
                this["RecordUserTracks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NetworkServerActive {
            get {
                return ((bool)(this["NetworkServerActive"]));
            }
            set {
                this["NetworkServerActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BroadcastLocationSources {
            get {
                return ((bool)(this["BroadcastLocationSources"]));
            }
            set {
                this["BroadcastLocationSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int MapZoomLvl {
            get {
                return ((int)(this["MapZoomLvl"]));
            }
            set {
                this["MapZoomLvl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MapOpacity {
            get {
                return ((int)(this["MapOpacity"]));
            }
            set {
                this["MapOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MapBearing {
            get {
                return ((int)(this["MapBearing"]));
            }
            set {
                this["MapBearing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51.4580686")]
        public double MapLat {
            get {
                return ((double)(this["MapLat"]));
            }
            set {
                this["MapLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.01476143")]
        public double MapLng {
            get {
                return ((double)(this["MapLng"]));
            }
            set {
                this["MapLng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoBrightness {
            get {
                return ((int)(this["VideoBrightness"]));
            }
            set {
                this["VideoBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoContrast {
            get {
                return ((int)(this["VideoContrast"]));
            }
            set {
                this["VideoContrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoSaturation {
            get {
                return ((int)(this["VideoSaturation"]));
            }
            set {
                this["VideoSaturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int QRCodePaperFormat {
            get {
                return ((int)(this["QRCodePaperFormat"]));
            }
            set {
                this["QRCodePaperFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoSourceIndex {
            get {
                return ((int)(this["VideoSourceIndex"]));
            }
            set {
                this["VideoSourceIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoFormatIndex {
            get {
                return ((int)(this["VideoFormatIndex"]));
            }
            set {
                this["VideoFormatIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MarkerBasedDetectorOriginalImage {
            get {
                return ((bool)(this["MarkerBasedDetectorOriginalImage"]));
            }
            set {
                this["MarkerBasedDetectorOriginalImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MarkerBasedDetectorEdgeImage {
            get {
                return ((bool)(this["MarkerBasedDetectorEdgeImage"]));
            }
            set {
                this["MarkerBasedDetectorEdgeImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MarkerBasedDetectorThresholdedImage {
            get {
                return ((bool)(this["MarkerBasedDetectorThresholdedImage"]));
            }
            set {
                this["MarkerBasedDetectorThresholdedImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MarkerBasedDetectorDrawMarkersOnVideo {
            get {
                return ((bool)(this["MarkerBasedDetectorDrawMarkersOnVideo"]));
            }
            set {
                this["MarkerBasedDetectorDrawMarkersOnVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int MarkerBasedDetectorThreshold {
            get {
                return ((int)(this["MarkerBasedDetectorThreshold"]));
            }
            set {
                this["MarkerBasedDetectorThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string MarkerBasedDetectorMinMarkerSize {
            get {
                return ((string)(this["MarkerBasedDetectorMinMarkerSize"]));
            }
            set {
                this["MarkerBasedDetectorMinMarkerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string MarkerBasedDetectorMaxMarkerSize {
            get {
                return ((string)(this["MarkerBasedDetectorMaxMarkerSize"]));
            }
            set {
                this["MarkerBasedDetectorMaxMarkerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedDetectorIndex {
            get {
                return ((int)(this["SelectedDetectorIndex"]));
            }
            set {
                this["SelectedDetectorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColorBasedDetectorShowColorImage {
            get {
                return ((bool)(this["ColorBasedDetectorShowColorImage"]));
            }
            set {
                this["ColorBasedDetectorShowColorImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColorBasedDetectorDrawBoundingBoxed {
            get {
                return ((bool)(this["ColorBasedDetectorDrawBoundingBoxed"]));
            }
            set {
                this["ColorBasedDetectorDrawBoundingBoxed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ColorBasedDetectorColorTolerance {
            get {
                return ((int)(this["ColorBasedDetectorColorTolerance"]));
            }
            set {
                this["ColorBasedDetectorColorTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string ColorBasedDetectorMinObjectSize {
            get {
                return ((string)(this["ColorBasedDetectorMinObjectSize"]));
            }
            set {
                this["ColorBasedDetectorMinObjectSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string ColorBasedDetectorMaxObjectSize {
            get {
                return ((string)(this["ColorBasedDetectorMaxObjectSize"]));
            }
            set {
                this["ColorBasedDetectorMaxObjectSize"] = value;
            }
        }
    }
}
